### ISSUE TITLE
No .dmb output without any error messages

### ISSUE THREAD

**Issue by Adrian-UCL** [asalmon91/ARFS-2-Batch#5]
After running the script, there's no .dmb file generated. Neither is there any error given explicitly. 
The running process seems sensible as it does take some time to compute the matrix during each run. 
The only output items are a .mat file, stdout.txt and an empty "log.txt" created in the original folder where the input .dmb files are kept. 
Versions of used software: 
OS: Microsoft Windows 10 Enterprise 10.0.19043 Build 19043
Matlab: 9.1.0.1012177 (R2016b) Update 7
Python: 
![image](https://user-images.githubusercontent.com/103220518/162328038-1a72e3e0-3d6f-4fe6-8472-19fc937a3ab8.png)
(various versions installed with Python 3.10.2 returned in PowerShell with a "python -V" command)
Approaches tried so far: testing with different samples and datasets, separating OD and OS, reinstalling Python & Matlab
Yet none above has succeeded unfortunately.

**Comment by asalmon91** [comment]
As a temporary fix, please try setting you PATH environment variable such that the python 2.7.18 version precedes the 3.10.2 version. ARFS will try to execute python from the command line, so if it reaches v3 before v2.7 it will not work.

**Comment by Adrian-UCL** [comment]
Dear Alex, 
Thank you for suggesting the above solution. 
Unfortunately, I've tried that method but still to no avail. 
We'd be most grateful if you could point out anything else that you think is also worth trying and direct us to the right way. 
Many thanks, 
Adrian

**Comment by Adrian-UCL** [comment]
Issue resolved—the solution was to replace the original 'makeDmbs.m' file located inside 'fx' with the one attached. 
[makeDmbs.zip](https://github.com/asalmon91/ARFS-2-Batch/files/11576879/makeDmbs.zip)
